### ISSUE TITLE
Delay use of cert during renewal

### ISSUE THREAD

**Issue by craigfrancis** [icing/mod_md#1]
When renewing a cert (e.g. 14 days before expiry), it can be useful to delay using the new cert for 24 hours.

This is because the cert contains a "valid from" date, and it's quite common for users accessing the site to have their computers clock be wrong... if it's out by days, there isn't much you can do about that (but hopefully that's more obvious that it needs to be fixed), whereas being out by hours is more tricky.

A classic example is a computer that has been incorrectly configured to use UTC, so it does not alter the time from "local time" when comparing the UTC value in the cert.

Some CA's do round the "valid from" date back a bit to address this, but if memory serves, LE does not.

**Comment by bazzadp** [comment]
+1. Could also help if you ever wanted to implement HTTP Public Key Pinning (HPKP). Personally I don't like HPKP (risk too high compared to protection it gives - for most sites) but short lived pinning or report-only pinning could work if automated through mod_md.

**Comment by craigfrancis** [comment]
You don't need to change the key with Let's Encrypt, so it is possible to use a static HPKP and just keep getting new certs (e.g. I use [acme-tiny](https://github.com/diafygi/acme-tiny)).

But I agree, I think HPKP is typically too dangerous for most websites.

**Comment by bazzadp** [comment]
Personally I think key reuse is bad practice, though do understand that perfect forward secrecy makes that less risky, it still seems wrong to me.

Currently I have a script that renews the cert with new key, adds Pins (in read-only mode as do find that useful as mentioned before), then restarts Apache to start publishing the new header, then 24 hours later after new header should be in use, it updates the certs and restarts Apache again. That way I don't get false alerts for HPKP-read-only and also avoid any time delay issues as you stated. Would love for that to be fully automated in future rather than the hacky script I have for that (what was more created to prove to myself it could be done rather than something I'd recommend anyone to do).

Anyway getting waaaay off topic. Just saying it's another possible use case, at some point, for delayed use of renewed certs.

**Comment by icing** [comment]
Thanks for all the advice. I agree that delaying the activation by a day seems prudent. That could become part of the staging process. I archive the previous data, so it is possible to keep on using that for a time. After all, the paths are handed out by ```mod_md```at server start.

On reuse of private keys, I share @bazzadp's concerns. Reading up on HKPK from [this article](https://timtaubert.de/blog/2014/10/http-public-key-pinning-explained/) by TIm Taubert, I understand that you use a ```max-age``` of 24 hours? And then announce the sha-256 of the new key in the headers 24 hours before switching certs? Sounds do-able.

**Comment by bazzadp** [comment]
Yup. Now 24 hours HPKP doesn't really offer that much protection to be honest, but I more use it for read-only version as an alerting backup to Certificate Transparency to offer another way to see illegitimate certs in the wild. So far I've found it never guess false positives so it's not noisy, but then I'm not a high profile site.

It's just with certain online security tools ([SSLLabs](https://www.ssllabs.com/ssltest/), [securityheaders.io](https://securityheaders.io), [hardenize.com](https://www.hardenize.com)) pushing HPKP ([dangerously in my opinion](https://www.tunetheweb.com/blog/dangerous-web-security-features/)!) it would be nice to have a safer way to do this for people who "chase a grade", as they are otherwise great tools. On that note in no way should this be on by default!

But, as I say, these are somewhat separate to the original request but perhaps something to think about if implementing this.

**Comment by craigfrancis** [comment]
@bazzadp Just a quick note to say I agree. I re-use keys for a year (ish), and that's because it's a manual process at the moment, with a 30 day max-age, it's not in [report-only](https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning#Report-Only_header) mode, and we have about ~1,000 orders per day... and while I do this, I don't suggest anyone else does, it's risky.

**Comment by icing** [comment]
So, test cases for this are not good yet, but the feature is in v0.7.0: report/restart and therefore activation of new certificates is delay by notBefore + 24h (max until the existing one expires).

**Comment by cpu** [comment]
> Some CA's do round the "valid from" date back a bit to address this, but if memory serves, LE does not.

Just a quick note since I happened to see this: Let's Encrypt **does** backdate the valid from date by 1 hour.

**Comment by icing** [comment]
Thanks @cpu! I think I'll leave the current 24h logic in there. Cannot harm *iff* the old cert is still valid. And otherwise the delay does not take effect (all bugs are mine).
