### ISSUE TITLE
Wiki still contains ManagedDomain instead of MDomain

### ISSUE THREAD

**Issue by boldt** [icing/mod_md#100]
E.g. https://github.com/icing/mod_md/wiki

```
ManagedDomain your_domain.de
```

**Comment by icing** [comment]
Thanks. Fixed the locations I found.

**Comment by icing** [comment]
Ok, thanks.

Btw. you got probably confused by my "simplify" migration advice (now removed) that only worked for Apache trunk (never in 2.4.x), but was rejected by the project and will not happen. VirtualHosts for several ports with mixed http: and https: will not work.

If you follow the example with the 2 VirtualHosts on that page, you should find a working setup. Otherwise I advise the users apache httpd mailing list.
