### ISSUE TITLE
AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! after migrating to 2.0.1

### ISSUE THREAD

**Issue by Bagu** [icing/mod_md#125]
Hello,

Maybe related with this : https://github.com/icing/mod_md/issues/94
But not sure.

After upgrading from 1.1.7 to 2.0.1 without any other change, i receive this errors : 
`[Sat Jun 01 18:02:11.467856 2019] [ssl:error] [pid 4676:tid 664] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=Apache Managed Domain Fallback / issuer: CN=Apache Managed Domain Fallback / serial: 67AB5A455D2E5289FE4EFBD707CB73FA361D88C7 / notbefore: May 29 19:48:11 2019 GMT / notafter: Jun 12 19:48:11 2019 GMT]
[Sat Jun 01 18:02:11.467856 2019] [ssl:error] [pid 4676:tid 664] AH02604: Unable to configure certificate hyze.fr:443:0 for stapling`

Here is my httpd-md.conf : 
`LogLevel warn md:info ssl:error

# Container for directives applied to the same managed domains
MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf

# which ACME challenge types shall be used
#MDCAChallenges tls-sni-01 http-01
MDCAChallenges http-01

MDRequireHttps permanent

MDomain hyze.fr blog.hyze.fr forum.hyze.fr
MDomain mch44.fr www.mch44.fr
MDomain bagu.fr www.bagu.fr dolibarr.bagu.fr webmail.bagu.fr autoconfig.bagu.fr
MDomain bagu.biz www.bagu.biz webmail.bagu.biz autoconfig.bagu.biz blog.bagu.biz genealogie.bagu.biz isabelle.bagu.biz`

And i have set this to httpd-ssl.conf : 
`# OCSP Stapling, only in httpd 2.3.3 and later
SSLUseStapling          on
SSLStaplingResponderTimeout 5
SSLStaplingReturnResponderErrors off
MDMustStaple on`

Other domains don't trow any error.

Do you have any idea about why this happen ?

**Comment by icing** [comment]
The log entry `Unable to configure certificate hyze.fr:443:0 for stapling` is unfortunately happening when a fallback certificate is used. I should make a fix in mod_ssl in the future to avoid this. However, even though an error is logged, the server will work through this.

The question here is why there was not valid certificate already for `hyze.fr`. You say that you migrated from `mod_md` v1.1.7 to v2.0.1 and if there was a LetsEncrypt certificate for `hyze.fr`earlier, the new version of mod_md should just have continued using it. As it seems to have happened for other domains.

So, I'd like to verify: 
 * did you already have a mod_md ceritificate for `hyze.fr` before upgrading the version?
 * I notice that `hyze.fr` is hosted by cloudflare. If you had an LetsEncrypt certificate before, was this obtained in the same cloudflare setup that you have now?

**Comment by Bagu** [comment]
Hello,

1. Yes, i already have a mod_md certificate for hyze.fr
2. But I recently changed my cloudflare account for this domain

In fact, the ownership of this domain was transmitted to me very recently, and I did the transfer shortly before the migration to version 2.0.1 of mod_md.

**Comment by icing** [comment]
If you enable the `server-status` handler somewhere, ([see documentation](https://httpd.apache.org/docs/2.4/mod/mod_status.html) and open it in your browser, it will list also all Managed Domains.

This would be interesting to see. If you do not like to share that, you can email me at stefan at eissing.org.

I presume that there is some mixup with mod_md, Let's Encrypt and the cloudflare setup. If cloudflare redirects your domains to its CDN (looks like it to me), and your server runs "behind" them, it will not necessarily see the challenge verifications sent by Lets Encrypt.

Also, if you raise the log level via

```
  LogLevel md:trace2
```

the error log should state pretty verbose what is going with that domain. Since logs are often sensitive, you could mail me that to the same address. Thanks!

**Comment by JBlond** [comment]
In the old days if was because of the missing CA cert. Do you use the fullchain cert? 
```
SSLCertificateFile conf/certs/fullchain.pem     
SSLCertificateKeyFile conf/certs/privkey.pem

```

**Comment by icing** [comment]
Ah, thanks. That helped.

The problem is  that I tried to do less in v2.0.x during startup. Problem is that name changes were no longer detected that way. I bet you do not have a directory `md/domains/hyze.fr/` in your filesystem, but `forum.hyze.fr` or the blog.hyze.fr one. 

No need to change anything, I am just making a v2.0.2 that reverts to the old initialization and that should make the error go away. I am thinking about doing an auto-rename in the store, but that may come in a later version.

Next release soon.

**Comment by icing** [comment]
Please check if v2.0.2 resolves your issue.

**Comment by Bagu** [comment]
I need the nono303 build to do this ;)
I'm under windows x64.

@JBlond I don't use fullchain cert ;)

**Comment by Bagu** [comment]
I can't do the test because of this : 
[Mon Jun 03 17:03:26.176528 2019] [md:trace1] [pid 7880:tid 2500] md_acme.c(331): response: 429
[Mon Jun 03 17:03:26.176528 2019] [md:warn] [pid 7880:tid 2500] (70013)Missing parameter for the specified command line option: acme problem urn:acme:error:rateLimited: Error creating new authz :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/

**Comment by icing** [comment]
Which tests? All you certificates were valid until August! Did you remove them every time? There is no need to do that, you know?

As you found out, if you do that too often, LE does rate limit you. This limit lasts for a week, but with a sliding window. So when the first attempt is a week old, it gets deducted from your limit.

**Comment by Bagu** [comment]
the v2.0.3 seem to work fine, no error for the moment.

Thanks a lot

**Comment by icing** [comment]
:-D
