### ISSUE TITLE
Possibility to use single account for all MDomain?

### ISSUE THREAD

**Issue by petr666** [icing/mod_md#128]
Hi,
is there any option, or is it possible to add one, to use same account for all MDomain declarations? Or declare which account should be used for each MDomain declaration (like declaring account in separate tag MDAccount with custom label which can than be referred from MDomain).
If I understand https://letsencrypt.org/docs/rate-limits/ correctly, with single account it should be possible to register 300 new domains per 3 hours, however since unique account is generated per MDomain, we are limited to registering 10 per 3 hours. That is huge difference. Also it is not possible to conform to recommendation to use only single account for hosting providers (https://letsencrypt.org/docs/integration-guide/).

**Comment by icing** [comment]
What you are seeing is a limitation in v1.x which is rather unfortunate:

 * if you start without an account and 10 MDomains, each domain will not find an existing one and create a new one.
 * if you start with 1 MDomain, get the certificate, reload the server, the new account gets accepted and all future MDomains will reuse it.

In Version v2.x this was fixed and one can start with as many domains as you want and only a single account is created. 

This was never noticed for a long time, since most people try 1 MDomain first and switch the others after that was successful. What you can do now (after making a backup of our md store files):

 * either throw away the complete md store directory and start fresh with only one MDomain. Enable all others after that was successful.
 * Edit all the `md.json` files in your store and replace the "account" entry with the one you want to keep. This will then be used on the next renewal. Remove all other account directories in store.

```
{
  "name": "mydomain.com",
  ...
  "ca": {
    "account": "ACME-localhost-0000",
  }, ...
}
``` 

Does this help?

**Comment by petr666** [comment]
Great, thanks for quick response.
I'm testing some concept where new domains will be dynamically added by separate vhost conf files, so I've started right away with multiple domains. Additionally I'm testing behavior on localhost, so I'm not actually able to finish verification and obtain certificate.
So in case it works as you described it, it will be sufficient for my case.
