### ISSUE TITLE
Responding to HTTP challenges statelessly

### ISSUE THREAD

**Issue by alexzorin** [icing/mod_md#130]
I guess this is tangentially related to #128 

The use case here is an environment that is composed of multiple httpd servers in an active/standby fashion for a set of domains.

At the moment, only active servers can issue and renew certificates because of two reasons:

- Each mod_md installation uses a different ACME account key, resulting in a different challenge response between servers.
- Only known challenge tokens are responded to - the challenge token must have been previously registered with `md_store_save(..., MD_SG_CHALLENGES, ...)`.

What I would love to see is the ability for both active and standby servers to be able to issue certificates, regardless of their role. 

In other web servers, this can be achieved [rather elegantly](https://github.com/Neilpang/acme.sh/wiki/Stateless-Mode) by reflecting the requested challenge token alongside the known JWK thumbprint.

In mod_md, I think this would require two things to change:

- [ ]  Allow mod_md to be configured with an ACME account key (`MDCAPrivateKeyFile` (optional))
- [ ] Eschew the store/load tracking of HTTP-01 challenges and respond to them statelessly. 

My only hesitation about this is that it introduces a mode of operation that is only valid for HTTP, not for TLS-ALPN. That may be torpedoing your laudable goal of keeping it simple and easy to use.

On the other hand, this is an advanced, multi-serve use case that people are not exactly going to walk into by accident.  It can be fully described and documented on a wiki/whatever page.

And if you are amendable to implementing it, you may be one of the only ACME clients in existence that make addressing this use case easy!

**Comment by icing** [comment]
Hey @alexzorin ,

I like the idea of configuring an account key. I know that Let's Encrypt matches JWS keys to accounts, so that a client can detect its account url. I'd have to look of the ACME protocol itself says anything about that (interoperability).

As to the "stateless" setup: hmmm. 

 * the acme.sh example you linked means that anyone can find your thumbprint just by GET on /.well-known/acme-challenge/123. I am not sure if this is a good idea.
 * you are right that this would not work for other challenge types

I think the real solution would be a `mod_md` store that does not use the file system but a central storage accessible from all your server instances. Would that address the user case, should be ever find such a magical thing?

**Comment by alexzorin** [comment]
Hey, thanks for the quick response.

>anyone can find your thumbprint

I don't think that JWK thumbprints are considered sensitive information in ACME. At least, they are already the result of cryptographic digest and are sent over a cleartext port anyway. I've seen a few major providers and SaaS expose their thumbprints in this way (like OVH).

>not use the file system but a central storage accessible from all your server instances

Well, yes. For example, this is what projects like Caddy do - it can persist certificate data to Consul and places like that. But it attracts a high complexity cost - you probably won't want a repository of storage backends in your source tree just for this one exotic feature. I was hoping to jump on the opportunity to avoid sharing state entirely thanks to HTTP-01's design.

But I fully accept if you don't feel like jumping on the stateless train ;) .

**Comment by icing** [comment]
Do not write me off yet! I'd like to check these things with the ACME working group...if they agree to your security assessment, the `http-01` challenge responder could be made simpler.

There are some other internal changes necessary for the fixed account key, though...

**Comment by jmwebservices** [comment]
> The use case here is an environment that is composed of multiple httpd servers in an active/standby fashion for a set of domains.

I am also in favor of this request. My setup is similar except that the standby server is actually online and public facing. Where the active server is reachable at **www.domain.com**, the standby is at **standby.domain.com**. When the active server needs maintenance, we simply swap A records for the switch.

@icing am I correct to assume that `mod_md`, in its current state, will fail to issue certificates on each server? Since the servers are mirrors, they actually share the same configuration file. This is what I had in mind:

```
MDomain www.domain.com standby.domain.com
<VirtualHost IP_www.domain.com IP_standby.domain.com>
   ServerName www.domain.com
  ServerAlias standby.domain.com
</VirtualHost>
```
Would the above fail?

**Comment by icing** [comment]
Yes. The domain authorizations, performed by Lets Encrypt, would not complete on both server, since challenges for one of the domains is made to the "other server". I believe that certbot and other clients would also have problem with such a setup.

If the feature requested here would be implemented, `http-01` challenges could be answered by both machines - *IF* they shared the ACME account key. And you'd need to control somehow which of the two does renewals - with a standby as well, obviously.

**Comment by jmwebservices** [comment]
Thanks for the quick reply.

**Comment by icing** [comment]
Cleaning up my issues list: this situation can now be resolved by using `MDMesssageCmd`to register a script that distributes challenge files among servers.

The script would act on the `challenge-setup:*` arguments to copy/rsync the files from `md/challenges` to the other server. When the script returns after copying, the other server will be able to answer the ACME challenges.
