### ISSUE TITLE
MDNotifyCmd no longer allowed in MDomainSet

### ISSUE THREAD

**Issue by gittwe** [icing/mod_md#168]
I have upgraded from 2.0.9 to 2.2.5 and get a syntax error when starting apache: 

`MDNotifyCmd is not allowed inside an '<MDomainSet' context`

I found MDNotifyCmd quite handy to trigger apache restarts or script based installations of mail server certificates. 

`
<MDomain example.com>
  MDNotifyCmd restart_server.sh apache
</MDomain>
`

`<MDomain mail.example.com>
  MDNotifyCmd install_mail_cert.sh postfix
</MDomain>`

Is this no longer a valid option or did I miss something?

**Comment by icing** [comment]
`MDNotifyCmd` has always been a global setting, but did not check being used inside a `MDomain` before. When you set it twice, the last one just overwrites the previous, I'm afraid.

Since the script is called with the MDomain name as argument, a global instance seemed sufficient to me. Also, in 2.2.x the commands are invoked for a single MDomain at a time.

Maybe have a look at the new `MDMessageCmd` which gives the script information about what happened to a domain.

I am open to suggestions on how to improve this area and its documentation.
