### ISSUE TITLE
Config with no vhosts ?

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#18]
There are admin/users around who have no vhosts in a SSL-Front, the back has the Vhosts. 

Does this work ? They like to run mod_md in the Front.

A typical config in this case is:

==443==> Front minimal apache listen 443 and no vhosts =====Proxypass==> 80===>Back with all the vhosts and no ssl

I saw that with 0.3.0  "tls-sni-01" is supported and with 0.3.0+ there is 'MDDriveMode always'.
I cannot test it, because 0.3.0 gives compile errors (see other issue).

**Comment by icing** [comment]
At the moment, this does not work because ```mod_md``` has no knowledge that the default host is responsible for this domains.

On your setup and with v0.5.0 deployed on your TLS server (what you call "fron"), you should be able to add to your config:

```
  ManagedDomains name1 name2 name3...
  MDDriveMode always
```
and ```mod_md``` will contact Let's Encrypt to get a certificate covering all names. You could then add those files with the standard ```SSLCertificate*``` directives to your server. Which would be a nice test. 

***BUT ATTENTION***: since we are in alpha testing, the certificates are from the Let's Encrypt testing service and are not valid in a browser. So, please do not try to run your live server with them.

**Comment by SteffenAL** [comment]
Issue overlaps with issue #15 , so closing.
