### ISSUE TITLE
Mod_md can't get certificate, but showed status say : ok

### ISSUE THREAD

**Issue by Bagu** [icing/mod_md#181]
Hello,

I have mod_md 2.2.6 (same problem with 2.2.7) with apache 2.4.41 and fcgid 2.3.10.
I have this in status :

mch44.fr | mch44.fr www.mch44.fr | good | until 2020-05-14 | Let's Encrypt | on | crt.sh | Renew 2020-04-15

mch44.fr | d57583990ddbac80d38b302814e046fb12bb3994 | good | until 2020-02-21 | ocsp.int-x3.letsencrypt.org | Refresh 2020-02-19

But, when i click on crt.sh, i get "Certificate not found" and the website work on http, but not on https protocol.
There is no error message, nothing else i can check, and other managed websites are ok...
What am i missing ?

**Comment by icing** [comment]
https runs on port 443 and that is open on www.mch44.fr. But the SSL is not configured there and it just talks unencrypted http. Did you configure `SSLEnging on` in that VirtualHost?

Additional SSL information you can find [in this howto](https://httpd.apache.org/docs/current/ssl/ssl_howto.html) and other places.

**Comment by Bagu** [comment]
But, SSLEngine is set to "ON"
`<VirtualHost *:443>
	ServerName mch44.fr
	DocumentRoot /path/mch44/html/www

	SSLEngine On

	ServerAlias mch44.fr www.mch44.fr
	VirtualDocumentRoot /path/mch44/html/%1

	RewriteEngine On
	RewriteCond %{HTTP_HOST} ^mch44.fr [NC]
	RewriteRule ^ %{REQUEST_SCHEME}://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

	<IfModule fcgid_module>
		<Files ~ "\.php$">
			AddHandler fcgid-script .php
			FcgidWrapper "/path/php/php-cgi.exe -d error_log=/path/logs/vhost_php_error/mch44.fr.php_error.log" .php
		</Files>
	</IfModule>

	ErrorLog /path/mch44.fr.apache.error.log

	<Directory /path/mch44/html/>
		Options +FollowSymLinks -Indexes -Includes -ExecCGI
		AllowOverride all
		Require all granted
	</Directory>
</VirtualHost>`

And others domains are ok...This is why i'm saying i must miss something, but it's harder than that ;)

**Comment by advorkin** [comment]
Hello,

Were you able to figure out this problem?  Thank you.

**Comment by Bagu** [comment]
Nop, still have the issue... I don't know why.
My other hosts are ok...

**Comment by tlhackque** [comment]
Your host **does** have a valid certificate, issued by `Let's Encrypt`:
````
# ssl_info www.mch44.fr
www.mch44.fr:443
    Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
    Issued : Feb 17 14:51:27 2020 GMT
    Expires: May 17 14:51:27 2020 GMT
    Subject: CN = mch44.fr
    Public Key Algorithm: rsaEncryption
    Subject Alternative Name:
            DNS:mch44.fr,
            DNS:www.mch44.fr

    Issuer: O = Digital Signature Trust Co., CN = DST Root CA X3
    Issued : Mar 17 16:40:46 2016 GMT
    Expires: Mar 17 16:40:46 2021 GMT
    Subject: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
    Public Key Algorithm: rsaEncryption

    New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
    Peer signature type: RSA-PSS
    Peer signing digest: SHA256
    Verification: OK
    Verify return code: 0 (ok)
````
The site returns ERR_BAD_SSL_CLIENT_AUTH_CERT.  This indicates that you require client authentication.

If you are using client authentication and tls-alpn-01, you need the patch to `mod_ssl` in #172 for renewal.

Your host specifies:
````
Acceptable client certificate CA names
C = US, O = "CloudFlare, Inc.", OU = Origin Pull, L = San Francisco, ST = California, CN = origin-pull.cloudflare.net
Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA224:RSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512
````
Your client needs to provide a compatible certificate issued by CloudFlare, or you'll get this error (`s_client` will report as "certificate required, number 116")  It is unlikely that CF (a CDN) is issuing you **client** certificates...

If you don't intend client authentication, you need to make sure you **don't have** `SSLVerifyClient require or optional` in scope.  (Note that TLS 1.3 doesn't support renegotiation, with optional may trigger.)

As Steffan indicated, this appears to be a configuration issue unrelated to `mod_md`.

**Comment by Bagu** [comment]
Hmm that's a real problem because i don't use cloudflare for this host (i use it for others)
And I do not manage the DNS zone of this host.
So, i there a way to make it working  ?

**Comment by tlhackque** [comment]
Again, this is not a `mod_md` issue.

Client authentication is when visitors to your site must have a certificate to access it.  (Like a password.)

You need to be sure that you want this, and learn about how this works.  From the content, it appears to be a public website announcing your services - you probably want `SSLVerifyClient none`

The reason cloudflare is being offered is because you used one of it's certificates in a
`SSLCACertificateFile` or `SSLCACertificatePath` directive, instead of the certificate(s) of the CA that issues your clients certificates.

This is a relatively advanced configuration - it's rarely used on public websites.
It's often used in enterprise environments, where the certificate is used for single-signon, sometimes with a hardware token.  You either setup a private CA, or pay for certificates for each user.  This is not the kind of certificate that Let's Encrypt offers.

If you want to pursue this, see https://httpd.apache.org/docs/current/ssl/ssl_howto.html for some information; Google will provide lots of tutorials on the subject.

You'll get more help in another forum.  Please close this issue - as far as I can tell, `mod_md` is doing the right things.

**Comment by Bagu** [comment]
Ok, i believe mod_md have something to do with it.
Thanks to point me where i was wrong. ;)
