### ISSUE TITLE
(22)Invalid argument: CA url for <domain> invalid (missing uri scheme): accepted

### ISSUE THREAD

**Issue by sbondo1234** [icing/mod_md#219]
Apache (2.4.38 on Debian) crashes on startup and writes this in `error.log`:
```
[md:error] [pid 42:tid xxx] (22)Invalid argument: CA url for <domain> invalid (missing uri scheme): accepted
[md:error] [pid 42:tid xxx] (22)Invalid argument: AH10073: synching 10 mds to registry
AH00016: Configuration Failed
```

There are `no files under the accounts, challenges or staging folders` and this is what's in my `md_store.json`:
```
{
    "store": {
        "version": 3.0
    },
    "key": "some key"
}
```

What could be causing this issue / How can I diagnose it further?

**Comment by icing** [comment]
The „accepted“ setting is a feature of the newer 2.x versions of the module. For older version you need to specify the link. I believe the following will work:

https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf

I recommend upgrading your version, since it probably uses the old ACME service endpoints. Lets Encrypt plans to shut them down this year.

**Comment by sbondo1234** [comment]
That was it, thanks.
