### ISSUE TITLE
Support the ACME test server "Pebble"

### ISSUE THREAD

**Issue by mkauf** [icing/mod_md#225]
[Pebble](https://github.com/letsencrypt/pebble) is an ACME test server. Its behaviour is deliberately different from [Boulder](https://github.com/letsencrypt/boulder) and it can be used to test ACME implementations like mod_md. From Pebble's README:
> In places where the ACME specification allows customization/CA choice Pebble aims to make choices different from Boulder. For instance, Pebble changes the path structures for its resources and directory endpoints to differ from Boulder. The goal is to emphasize client specification compatibility and to avoid "over-fitting" on Boulder and the Let's Encrypt production service.

Currently mod_md does not work with Pebble. Testing with Pebble is difficult, because it only supports encrypted connections (https) and mod_md has no feature to load a custom CA.

I modified Pebble to accept unencrypted connections (I can provide a patch). Then some more problems appeared. I modified Pebble to avoid these:
* ``Use POST-as-GET to retrieve account data instead of doing an empty update``
* ``Challenge response body contained legacy KeyAuthorization field, POST body should be {}``

Then this problem appeared when finalizing an order - no solution yet:
* ``Order's status ("valid") was not ready`` , debug messages of mod_md: ``while[Waiting for finalized order to become valid]``, ``cert not in response from http://...:4001/certZ/20a34eab1932c6f1``

It would be great if these issues could be addressed, this would improve the stability and interoperability of mod_md.

**Comment by mkauf** [comment]
> The first two that you mentioned were fixed in master this spring. Look for my commits.

Cool, thanks! The third problem is also fixed. Previously it was not possible to get any certificate, even with a fresh mod_md store directory. This works now :-)

>  the staging area has an account, but pebble has been restarted and doesn't know about that account. The error handling for that is broken - and rather involved

You're right. mod_md gets confused after a restart of Pebble.

Response of Pebble:
``
{
   "type": "urn:ietf:params:acme:error:accountDoesNotExist",
   "detail": "Account http://<acme-server>:4001/my-account/1 not found.",
   "status": 400
}
``

Log messages of mod_md:
```
(20014)Internal error (specific information not available): acme problem urn:ietf:params:acme:error:accountDoesNotExist: Account http://<acme-server>:4001/my-account/1 not found.
(20014)Internal error (specific information not available): <md-domain>: asked to retrieve chain, but no order in context
(20014)Internal error (specific information not available): AH10056: processing <md-domain>: Unable to retrieve rsa certificate chain.
```

**Comment by tlhackque** [comment]
If you restart `httpd` before restarting pebble, things will work somewhat better.

The issue is triggered when a (usually new) account is in the staging area, but does not exist on the ACME server.  This happens with Pebble because it has no persistent storage - all accounts are forgotten when it restarts.  

Restarting `httpd` will cause `mod_md` to move the nonexistent account to the active directory.  At that point it's safe to restart Pebble. The `accountDoesNotExist` error is handled better by `mod_md` when the account in question is in the active directory.  

This is not correct behavior for `mod_md` - it should handle this error correctly at any time.  But these steps may be a work-around for some cases.  As I mentioned, fixing it turns out to be involved.  It's on my list.

In realistic use cases (with production ACME servers), it is unlikely that this corner case will be encountered.  A new account vanishing in the window between creation and the next `httpd` restart would require manual intervention or extremely bad luck.

Of course, I agree that it needs to be fixed.  It's not a high priority.

Note that Pebble is useless for production - it is deliberately designed to discourage any use other than client testing.  This has been discussed in previous issues.  Pebble does stress clients and has identified interoperability issues, some of which affect ACME servers other than LetsEncrypt.  

Feel free to raise any other issues that you encounter.

**Comment by icing** [comment]
just push a version to master that runs with pebble. details in the README.

**Comment by icing** [comment]
Pebble as test server is now fully supported in master. Description on how to configure and use in README.
