### ISSUE TITLE
Better error message for ManagedDomain/VirtualHost mismatch

### ISSUE THREAD

**Issue by jsha** [icing/mod_md#33]
Per https://github.com/icing/mod_md/wiki/Edge-Cases#missing-names,

"While one MD may cover several VirtualHosts, it may never cover only part of one. All ServerName and ServerAlias names must be listed."

Intentionally configuring such a broken setup:

```
ManagedDomain powerdns.crud.net
MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf
<VirtualHost *:443>
ServerName powerdns.crud.net
ServerName misc.crud.net
...
```

Produces this error message:

```
[Sat Aug 19 15:47:31.158152 2017] [ssl:warn] [pid 1] AH: Init: (misc.crud.net:443) disabling this host for now as certificate/key data for the Managed Domain is incomplete.
```

Ideally this should say something like "Disabling misc.crud.net:443 because the corresponding ManagedDomain (powerdns.crud.net) doesn't include its hostname. Add misc.crud.net to the ManagedDomain directive to fix."

**Comment by icing** [comment]
I agree that log messages need to describe the problem in a better way and feedback is very much appreciated. Here, there are two things:

  1. The documentation was not updated. It is not default behaviour that a MD automatically includes all server names and aliases as defined in the ```VirtualHost```. This eliminates a unnecessary duplication and is what most users want (my assumption).
 1. The message cited tries to warn the user that a ManagedDomain is being disabled (e.g. requests are answered with 503, TLS handshakes might fail or be not accepted by clients) because the certificate is no yet available.

**Comment by icing** [comment]
I updated the wiki and will change the log message of mod_ssl to be clearer about this.

**Comment by jsha** [comment]
>  It is not default behaviour that a MD automatically includes all server names and aliases as defined in the VirtualHost

I assume you meant "it is *now* default behavior?" The new behavior in the updated wiki looks great:

> By default, a MD always accumulates all ServerName and ServerAlias domain names of all VirtualHosts that it matches

**Comment by icing** [comment]
Yes, sorry about the typo.
