### ISSUE TITLE
Clarification on "no auto restart"

### ISSUE THREAD

**Issue by jsha** [icing/mod_md#51]
In https://github.com/icing/mod_md/wiki#no-auto-restart-when-started-as-root, it says:

> No Auto Restart when started as root

> When httpd is started as root user by your system, as most *NIX distribution set it up, it is configured to have its children (the ones doing the actual work) run as a quite restricted user. On Ubuntu, this is commonly www-data. This is good for security, obviously.

> mod_md runs the ACME protocol also in these child processes and is therefore also restricted in the damages it can do. Which at the moment, also means it cannot signal the parent process to do a graceful restart. So, you will see a line in the error log that it was forbidden to do that. For now, in such a setup, you have to manually restart httpd for any certificate changes to take effect.

Does this include renewals, or just adding names to certificates? If it applies to renewals, it would be helpful to include practical advice here, like "run `service apache2 reload` in a daily root cronjob to ensure renewed certificates are loaded."

**Comment by icing** [comment]
I agree, this needs to be documented better.

**Comment by tlhackque** [comment]
Does this still apply, or was it fixed in V2?  If fixed, this issue should be closed.  Otherwise:

**Reload** - and even **graceful** - daily is not good in production environments.  59 of the 60 days of a renewal cycle, it has no purpose.  (At least for certificates.)  But it can be very expensive for large servers.

It seems to me that this could be better handled by having the parent watch for change (mtime || size || inode) in the certificate files.  This could be done infrequently to minimize cost - 30 min, 60 min, or daily.  **ntpd** does this hourly for its *leapsecond* file.  It could also limit the number of files checked each interval to smooth out the load - this might matter if you have hundreds or thousands of certificates.  (Does **mod_md** scale that high?)

Alternatively, isn't there a shared memory region that is used for session resumption?  [SSLSessionCache](https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslsessioncache) strongly recommends it.  A child process could post the name of a MD for which a new certificate has been received - the parent would gracefully terminate the processes that use it and run the **MDMessageCmd**.

A pipe could also be used - though it would be an inefficient use of file descriptors, especially with large servers (hundreds of child processes)...

**Comment by icing** [comment]
The daily reload is a recommendation for sites that can afford it. For other sites, I would advise making use of ```MDMessageCmd``` to act on new certificates in a timely manner. Also the new ```md-status``` handler makes certificate (and staged certificate) information available in JSON for a monitor.
