### ISSUE TITLE
Account-id in mod_md

### ISSUE THREAD

**Issue by marcelofrota2** [icing/mod_md#86]
Hi Dear, 

I have one small question about mod_md, i'm use mod_md in mywebserver, but i not locate some form, to put or configure the account-id from the lets encrypt in mod_md.

https://letsencrypt.org/docs/account-id/

Would be  possible configure  account-id in mod_md or this not possible and not used for mod_md ? 

Thanks a lot
Marcelo

**Comment by icing** [comment]
To my knowledge, the account id is generated by lets encrypt on registration and cannot be provided.

In order to use an existing account id in apache, the server would not only need the id, but also the private key. To prove that it is authorized.

It would be possible to add that in the configuration, but mod_md is currently not designed for it.

There are issues with how to handle changes. Assume it has already created an account and then another one is configured, the question is then when the new one should be used and for what.

Note that the account info is all stored in the md repository, should you have need to use it, eg for revocations.
