### ISSUE TITLE
Enable OCSP Stapling

### ISSUE THREAD

**Issue by marcelofrota22** [icing/mod_md#95]
Hi Dears,

I have one small question about mod_md. 

Can i active usestapling in my apache without problem with mod_md ? Existing some conf there i should put in conf mod_md for using with mod_md ?

I imagine, i  should put the options bellow in my apache, right ?

SSLUseStapling on
SSLStaplingResponderTimeout 120
SSLStaplingReturnResponderErrors off
SSLStaplingCache shmcb:/var/run/ocsp(128000)

Thanks a Lot!

**Comment by icing** [comment]
First of all, this is all handled by ```mod_ssl```. When you turn ```MDMustStable on``` it results only in the proper bit set in the certificate. But of course that requires the function to be enabled in ```mod_ssl```. (You seem to be aware, I just want to avoid confusion)

I myself run stapling with a persistent cache, like:
```
SSLStaplingCache        dbm:ocsp-stapling
```

That means that after a server restart/reload, the staple responses can be reused and do not need to be retrieved all over again. I personally also like a shorter timeout, since I prefer client requests to fail rather than hang around for 2 minutes. But that depends also of course on your sites requirements.
